version: "3"

services:
  dnsmasq:
    build: ./dnsmasq
    volumes:
      - ./data/pxe-config/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/os/rpi4_uefi_firmware/:/tftp/
      - ./data/pxe-config/x86_64_grub.cfg:/tftp/x86_64/grub.cfg
      - ./data/os/x86_64/EFI/BOOT/grubx64.efi:/tftp/x86_64/grubx64.efi
      - ./data/os/x86_64/images/pxeboot/initrd.img:/tftp/x86_64/initrd.img
      - ./data/os/x86_64/images/pxeboot/vmlinuz:/tftp/x86_64/vmlinuz
      - ./data/pxe-config/aarch64_grub.cfg:/tftp/aarch64/grub.cfg
      - ./data/os/aarch64/EFI/BOOT/grubaa64.efi:/tftp/aarch64/grubaa64.efi
      - ./data/os/aarch64/images/pxeboot/initrd.img:/tftp/aarch64/initrd.img
      - ./data/os/aarch64/images/pxeboot/vmlinuz:/tftp/aarch64/vmlinuz
    network_mode: host
    cap_add:
      - NET_ADMIN
  http:
    build: ./http
    network_mode: host
    volumes:
      - ./data/os:/usr/share/nginx/html/os
      - ./data/init-config/:/usr/share/nginx/html/init-config
    environment:
      NGINX_PORT: 80
