metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.1.200, mac: '18:66:da:42:c1:80', disk: sda, network_interface: eno1, arch: x86_64}
        metal1: {ansible_host: 192.168.1.68, mac: 'e4:5f:01:9c:ef:4e', disk: sda, network_interface: eno1, arch: aarch64}
        #metal2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1, arch: x64}
    workers:
      hosts:
        #metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f5:69', disk: sda, network_interface: eno1, arch: x64}
